language: java

before_install:
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
  - "sudo apt-get install graphviz 2>&1 | tail -n 2"
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/plantuml.jar
  - hg clone -r 8.6.7 https://asciidoc.googlecode.com/hg/ asciidoc-8.6.7

script:
  - cd sprint_5
  
  - SRCDIR=./src
  - BINDIR=./bin
  
  - java -jar ../plantuml.jar -Tpng -o srcdoc/images srcdoc/diag0.puml
  
  - echo /***** Compilation du modele *****/
  
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Modele/Sujets.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Modele/Etudiants.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Modele/Projets.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Modele/Intervenants.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Modele/Voeux.java
 
  - echo /***** Compilation doptilib *****/
 
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Lib/Optilib.java
 
  - echo /***** Compilation de linterface *****/
 
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/A_propos.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/AffichageEtu.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/AffichageInt.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/AffichageProj.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/AffichageSuj.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/AffichageGroupe.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/AffichageVoeux.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/Enregistrement.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/OuvrirEnregistrer.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/Recherche.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/AffichageVoeux.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Interface/FenetrePrincipale.java
  
  - echo /***** Compilation du controleur *****/
  
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Controleur/Controleur.java
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/Controleur/OptiMain.java
  
  - echo /***** Compilation dOptiWeb *****/
  
  - javac -cp .:./$SRCDIR -d $BINDIR $SRCDIR/OptiWeb/MakeOPTIweb.java

  - echo /***** Compilation des tests *****/
 
  - javac -cp .:./$SRCDIR:./$SRCDIR/junit.jar -d $BINDIR $SRCDIR/Test/TestsOptilib.java
  - javac -cp .:./$SRCDIR:./$SRCDIR/junit.jar -d $BINDIR $SRCDIR/Test/TestsControleur.java
  - javac -cp .:./$SRCDIR:./$SRCDIR/junit.jar -d $BINDIR $SRCDIR/Test/TestDoc.java
  - javac -cp .:./$SRCDIR:./$SRCDIR/junit.jar -d $BINDIR $SRCDIR/Test/MakeOPTIwebTest.java
  
  - echo /***** Génération doc *****/

  - python ../asciidoc-8.6.7/asciidoc.py -a data-uri -o srcdoc/docUtilisateurImage.html srcdoc/docUtilisateurImage.txt
  - python ../asciidoc-8.6.7/asciidoc.py -a data-uri -o srcdoc/docTechniqueImage.html srcdoc/docTechniqueImage.txt
  - python ../asciidoc-8.6.7/asciidoc.py -a data-uri -o srcdoc/presentationFinale.html srcdoc/presentationFinale.txt
  
  - echo /***** Tests java *****/
  - tree ./
  - java -cp .:./$SRCDIR:./$SRCDIR/junit.jar $BINDIR/Test/TestsOptilib
  - java -cp .:./$SRCDIR:./$SRCDIR/junit.jar $BINDIR/Test/TestsControleur
  - java -cp .:./$SRCDIR:./$SRCDIR/junit.jar $BINDIR/Test/TestDoc
  - java -cp .:./$SRCDIR:./$SRCDIR/junit.jar $BINDIR/Test/MakeOPTIwebTest
  
  - echo /***** MakeOPTIweb *****/
  
  - java -cp .:./$SRCDIR $BINDIR/OptiWeb/MakeOPTIweb
  
  - echo /***** Tests casperjs *****/
  
  - cd ./OPTIweb
  - casperjs test casperAccueil.js